[project]
name = "yat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask>=3.1.2",
    "pillow>=12.1.1",
    "torch>=2.10.0",
    "transformers>=5.1.0",
    "ultralytics>=8.4.14",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
